#server:
#  port: 443

#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-password: password

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ssafy-project.mysql.database.azure.com:3306/playground?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true
#    url: jdbc:log4jdbc:mysql://localhost:3306/playground?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: b309309*&
#    password: ssafy


  jpa:
    show-sq: true
    hibernate:
      ddl-auto: update # validate
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: i8b309.p.ssafy.io # localhost
      port: 6379


oauth2:
  api_gateway_url: "https://i8b309.p.ssafy.io" # "http://localhost:8080"
  client:
    registration:
      client-id:
        kakao: 0ec9e81052acada4b61a0e98229b431d
